<?php

?>

<!DOCTYPE html>
<html>

<?=$snippets["head_and_theme"]?>

<body>
    
    <?=$snippets["header"]?>

    <div class="bottom">

        <?=$snippets["navi"]?>
        
        <div class="desc">

            <!-- Admin area -->
            <?php if($params["user_params"]["is_admin"]): ?>
            <div>
                <a class="admin_link" href="<?= site_url('instructions-update_instructions') ?>">Päivitä ohjeita</a>
            </div>
            <?php endif ?>
            <!---->

            <!-- First headline -->
            <h2 class="text_headline">
                Miten käyttää...
            </h2>
            <div class="text">
                <div class="text_with_whitespace"><?= $params["texts"]["desc_instructions"] ?></div>
            </div>
            <!---->

            <!-- Git -->
            <h3 class="text_headline" id="git">
                Gitiä
            </h3>
            <div class="text">
                <div class="text_with_whitespace"><?= $params["texts"]["instructions_git"] ?></div>
            </div>
            <!---->

            <!-- Linux -->
            <h3 class="text_headline" id="linux">
                Linuxia
            </h3>
            <div class="text">
                <div class="text_with_whitespace"><?= $params["texts"]["instructions_linux"] ?></div>
            </div>
            <!---->

            <!-- Sublime Text -->
            <h3 class="text_headline" id="sublimetext">
                Sublime Textiä
            </h3>
            <div class="text">
                <div class="text_with_whitespace"><?= $params["texts"]["instructions_sublimetext"] ?></div>
            </div>
            <!---->

            <!-- Selenium -->
            <h3 class="text_headline" id="selenium">
                Seleniumia
            </h3>
            <div class="text">
                <div class="text_with_whitespace"><?= $params["texts"]["instructions_selenium"] ?></div>
            </div>
            <!---->


            <!-- Second headline -->
            <h2 class="text_headline" id="desc2">
                Ja miten perustan nettiservun
            </h2>
            <div class="text">
                <div class="text_with_whitespace"><?= $params["texts"]["desc_instructions2"] ?></div>
            </div>
            <!---->

            <!-- EC2 -->
            <h3 class="text_headline" id="ec2">
                EC2
            </h3>
            <div class="text">
                <div class="text_with_whitespace"><?= $params["texts"]["instructions_ec2"] ?></div>
            </div>
            <!---->

            <!-- Nginx -->
            <h3 class="text_headline" id="nginx">
                Nginx
            </h3>
            <div class="text">
                <div class="text_with_whitespace"><?= $params["texts"]["instructions_nginx"] ?></div>
            </div>
            <!---->

            <!-- PHP -->
            <h3 class="text_headline" id="php">
                PHP
            </h3>
            <div class="text">
                <div class="text_with_whitespace"><?= $params["texts"]["instructions_php"] ?></div>
            </div>
            <!---->

            <!-- MySql -->
            <h3 class="text_headline" id="mysql">
                MySql
            </h3>
            <div class="text">
                <div class="text_with_whitespace"><?= $params["texts"]["instructions_mysql"] ?></div>
            </div>
            <!---->

            <!-- TablePlus -->
            <h3 class="text_headline" id="tableplus">
                TablePlus
            </h3>
            <div class="text">
                <div class="text_with_whitespace"><?= $params["texts"]["instructions_tableplus"] ?></div>
            </div>
            <!---->
        </div>
    </div>

    <?=$snippets["footer"]?>

<script type="text/javascript" src=<?= site_url("js/scripts.js") ?>></script>
</body>
</html>
