<!DOCTYPE html>
<html>

<?=$snippets["head_and_theme"]?>

<body>
        
    <?=$snippets["header"]?>

    <div class="bottom">

        <?=$snippets["navi"]?>
        
        <div class="desc">

            <form method="POST" action="<?= site_url("instructions-update_instructions") ?>">
                <!-- Page text area -->
                <div>
                    <h2 class="main_text_headline">
                        Muokkaa ohjetta
                    </h2>
                    <p class="text">
                        <textarea name="desc_instructions_text" class="update_box"><?= $params["texts"]["desc_instructions"] ?></textarea>
                    </p>
                </div>
                <!---->

                <!-- Git -->
                <h3 class="text_headline" id="git">
                    Gitiä
                </h3>
                <div class="text">
                    <textarea name="instructions_git_text" class="update_box"><?= $params["texts"]["instructions_git"] ?></textarea>
                </div>
                <!---->

                <!-- Update button -->
                <button type="submit" name="update_desc_instructions_button" class="button update_button">
                    Päivitä
                </button>
            </form>

            <!-- Cancel button -->
            <a href="<?= site_url("instructions") ?>">
                <button class="button cancel_button">
                    Peruuta
                </button>
            </a>
        </div>
    </div>

    <?=$snippets["footer"]?>

<script type="text/javascript" src=<?= site_url("js/scripts.js") ?>></script>
</body>
</html>