<!DOCTYPE html>
<html>

<?=$snippets["head_and_theme"]?>

<body>
        
    <?=$snippets["header"]?>

    <div class="bottom">

        <?=$snippets["navi"]?>
        
        <div class="desc">

            <form method="POST" action="<?= site_url("instructions-update_instructions") ?>">
                <!-- Page text area -->
                <div>
                    <h2 class="main_text_headline">
                        Muokkaa ohjetta
                    </h2>
                    <p class="text">
                        <textarea name="desc_instructions_text" class="update_box"><?= $params["texts"]["desc_instructions"] ?></textarea>
                    </p>
                </div>
                <!---->

                <!-- Git -->
                <h3 class="text_headline" id="git">
                    Gitiä
                </h3>
                <div class="text">
                    <textarea name="instructions_git_text" class="update_box"><?= $params["texts"]["instructions_git"] ?></textarea>
                </div>
                <!---->

                <!-- Linux -->
                <h3 class="text_headline" id="linux">
                    Linuxia
                </h3>
                <div class="text">
                    <textarea name="instructions_linux_text" class="update_box"><?= $params["texts"]["instructions_linux"] ?></textarea>
                </div>
                <!---->

                <!-- Sublime Text -->
                <h3 class="text_headline" id="sublimetext">
                    Sublime Textiä
                </h3>
                <div class="text">
                    <textarea name="instructions_sublimetext_text" class="update_box"><?= $params["texts"]["instructions_sublimetext"] ?></textarea>
                </div>
                <!---->

                <!-- Selenium -->
                <h3 class="text_headline" id="selenium">
                    Seleniumia
                </h3>
                <div class="text">
                    <textarea name="instructions_selenium_text" class="update_box"><?= $params["texts"]["instructions_selenium"] ?></textarea>
                </div>
                <!---->


                <!-- Second headline -->
                <h2 class="text_headline" id="desc2">
                    Ja miten perustan nettiservun
                </h2>
                <div class="text">
                    <textarea name="desc_instructions2_text" class="update_box"><?= $params["texts"]["desc_instructions2"] ?></textarea>
                </div>
                <!---->

                <!-- EC2 -->
                <h3 class="text_headline" id="ec2">
                    EC2
                </h3>
                <div class="text">
                    <textarea name="instructions_ec2_text" class="update_box"><?= $params["texts"]["instructions_ec2"] ?></textarea>
                </div>
                <!---->

                <!-- Nginx -->
                <h3 class="text_headline" id="nginx">
                    Nginx
                </h3>
                <div class="text">
                    <textarea name="instructions_nginx_text" class="update_box"><?= $params["texts"]["instructions_nginx"] ?></textarea>
                </div>
                <!---->

                <!-- PHP -->
                <h3 class="text_headline" id="php">
                    PHP
                </h3>
                <div class="text">
                    <textarea name="instructions_php_text" class="update_box"><?= $params["texts"]["instructions_php"] ?></textarea>
                </div>
                <!---->

                <!-- MySql -->
                <h3 class="text_headline" id="mysql">
                    MySql
                </h3>
                <div class="text">
                    <textarea name="instructions_mysql_text" class="update_box"><?= $params["texts"]["instructions_mysql"] ?></textarea>
                </div>
                <!---->

                <!-- TablePlus -->
                <h3 class="text_headline" id="tableplus">
                    TablePlus
                </h3>
                <div class="text">
                    <textarea name="instructions_tableplus_text" class="update_box"><?= $params["texts"]["instructions_tableplus"] ?></textarea>
                </div>

                <!-- Namecheap -->
                <h3 class="text_headline" id="namecheap">
                    Namecheap
                </h3>
                <div class="text">
                    <textarea name="instructions_namecheap_text" class="update_box"><?= $params["texts"]["instructions_namecheap"] ?></textarea>
                </div>

                <!-- Certbot -->
                <h3 class="text_headline" id="certbot">
                    Certbot
                </h3>
                <div class="text">
                    <textarea name="instructions_certbot_text" class="update_box"><?= $params["texts"]["instructions_certbot"] ?></textarea>
                </div>

                <!-- Update button -->
                <button type="submit" name="update_desc_instructions_button" class="button update_button">
                    Päivitä
                </button>
            </form>

            <!-- Cancel button -->
            <a href="<?= site_url("instructions") ?>">
                <button class="button cancel_button">
                    Peruuta
                </button>
            </a>
        </div>
    </div>

    <?=$snippets["footer"]?>

<script type="text/javascript" src=<?= site_url("js/scripts.js") ?>></script>
</body>
</html>