<div class='footer'>
    <div class='footer_content_area'>
        <div  class='github_area'>
            <a href='https://github.com/Ropazio' target='_blank'>
                <!-- image from https://www.pngegg.com/en/search?q=github+Logo -->
                <button id='cat_button' type='button' alt='github logo'></button>
            </a>
        </div>
        <h4 class='footer_text'>Ropaz 2024</h4>
    </div>
</div>