
<!--------------------
                      
    Oh, Hi there!     
                      
    |\       /|       
    |,\_,,,_//\       
    /   ’;’     \     
   /  ^  ’  ^   \     
   |  0     0   /\    
   | =» T «=    //\   
    \,    o     //\   
      \,,,, \ \  //\  
    _    _ /\/\/\ //\ 
___|||__|||__________ 
--------------------- 
                      
--------------------->

<head>
    <meta charset='utf-8' name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' href=<?= file_path("styles", "main_page_styles.css") ?> />
    <link rel='stylesheet' href=<?= file_path("styles", $theme) ?> />
    <title><?= $title ?></title>
</head>
