<!DOCTYPE html>
<html>

<?=$snippets["head_and_theme"]?>

<body>
    
    <?=$snippets["header"]?>

    <div class="bottom">

        <?=$snippets["navi"]?>
        
        <div class="desc">
            <h2 class="text_headline">Tervetuloa Ropaz.dev:in pääsivulle!</h2>
            <p class="text">Tämä sivusto toimii niin sanottuna telakkana harrastuksiini liittyen; täältä voit löytää muun muassa linkit kuvauksineen joillekin muille verkkosivuilleni sekä kuvia ja peräti tekstiä joihinkin askarteluprojekteihini liittyen.
            <br>&emsp;
            Olen tehnyt sivulle myös "elämänhallinnaksi" kutsutun osion, joka sisältää sekä yleisen muistion sekä muistiot seuraavalle seitsemälle päivälle. Tämä ominaisuus kuitenkin vaatii kirjautumisen.
            <br>&emsp;
            Tällä hetkellä lähinnä pohdiskelen mitä muuta voisin sivustolle ladata...
            </p>
        </div>

    </div>

    <?=$snippets["footer"]?>

<script type="text/javascript" src=<?= file_path("js", "scripts.js") ?>></script>
</body>
</html>
