<?php

function show_blog_texts( array $blog_texts ) : void {

    if (empty($blog_texts)) {
        echo "<p class='text'>Ei päivittelyjä.</p>";
    } else {
        foreach ($blog_texts as $blog_text) {
            echo "<div class='text'>";
            echo    "<p class='blog_text_headline'>" . $blog_text["timestamp"] . "</p>";
            echo        "<div class='blog_text_box'>";
            echo        "<p>" . $blog_text["blog_text"] . "</p>";
            echo    "</div>";
            echo "</div>";
        }
    }
}

?>

<!DOCTYPE html>
<html>

<?=$snippets["head_and_theme"]?>

<body>
    
    <?=$snippets["header"]?>

    <div class="bottom">

        <?=$snippets["navi"]?>
        
        <div class="desc">

            <!-- Admin area -->
            <?php if($params["user_params"]["is_admin"]): ?>
            <div class="text">
                <a class="admin_link" href="<?= site_url('home-update_text') ?>">Päivitä sivun tekstiä</a>
                <a class="admin_link" href="<?= site_url('home-add_blog_text') ?>">Lisää päivittelyjä</a>
            </div>
            <?php endif ?>
            <!---->

            <!-- Home text area -->
            <h2 class="text_headline">
                Tervetuloa Ropaz.dev:in pääsivulle!
            </h2>
            <p class="text">
                <?= $params["texts"]["desc_home"] ?>
            </p>
            <!---->

            <!-- Blog text area -->
            <h3 class="text_headline">
                Päivittelyjä
            </h3>

            <?= show_blog_texts($params["blog_texts"]) ?>
            <!---->
        </div>
    </div>

    <?=$snippets["footer"]?>

<script type="text/javascript" src=<?= site_url("js/scripts.js") ?>></script>
</body>
</html>
