<!DOCTYPE html>
<html>

<?=$snippets["head_and_theme"]?>

<body>
    
    <?=$snippets["header"]?>

    <div class="bottom">

        <?=$snippets["navi"]?>
        
        <div class="desc">
            <h2 class="text_headline">
                Tervetuloa Ropaz.dev:in pääsivulle!
            </h2>
            <p class="text">
                <?= $params["texts"]["desc_home"] ?>
            </p>
        </div>

    </div>

    <?=$snippets["footer"]?>

<script type="text/javascript" src=<?= file_path("js", "scripts.js") ?>></script>
</body>
</html>
