<!DOCTYPE html>
<html>

<?=$snippets["head_and_theme"]?>

<body>
        
    <?=$snippets["header"]?>

    <div class="bottom">

        <?=$snippets["navi"]?>

        <div class="desc">
            <div>
                <h2 class="auth_headline">Tunnusten luonti</h2>
                <p class="text"></p>
            </div>
            <form method="POST" data-ajax="false" action="<?= site_url('create_account') ?>">
                <div class="text">
                    <div>
                        <div>
                            <h3 class="input_headline">Käyttäjänimi:</h3>
                        </div>
                        <div class="input">
                            <input type="text" id="username" name="username"/>
                        </div>

                        <div>
                            <h3 class="input_headline">Salasana:</h3>
                        </div>
                        <div class="input">
                            <input type="password" id="password" name="password"/>
                        </div>
                    </div>

                    <div id="create_account_button_box">
                        <button type="submit" class="button" name="login_button">Luo tunnus!</button>
                    </div>

                    <?php if(isset($_GET['error'])): ?> 
                    <div class="error">
                        <h3>Tunnusten luonti epäonnistui!</h3>
                        <p>Salasanan on oltava vähintään 10 merkkiä pitkä. Voit myös koittaa toista käyttäjänimeä.</p>
                    </div>
                    <?php endif ?>

                </div>
            </form>
        </div>   
    </div>

    <?=$snippets["footer"]?>

<script type="text/javascript" src=<?= file_path("js", "scripts.js") ?>></script>
</body>
</html>
