<!DOCTYPE html>
<html>

<?=$snippets["head_and_theme"]?>

<body>
        
    <?=$snippets["header"]?>

    <div class="bottom">

        <?=$snippets["navi"]?>

        <div class="desc">
            <div>
                <h2 class="auth_headline">Tunnusten luonti</h2>
                <p class="text">Tunnukset on nyt onnistuneesti luotu. Voit nyt kirjautua "Elämänhallinnassa" tullaksesi oman elämäsi herraksi.</p>
            </div>
        </div>   
    </div>

    <?=$snippets["footer"]?>

<script type="text/javascript" src=<?= site_url("js/scripts.js") ?>></script>
</body>
</html>
