<!DOCTYPE html>
<html>

<?=$snippets["head_and_theme"]?>

<body>
        
    <?=$snippets["header"]?>

    <div class="bottom">

        <?=$snippets["navi"]?>

        <div class="desc">
            <form method="POST" data-ajax="false" action="<?= site_url('login') ?>">
                <div class="text">
                    <div>
                        <div>
                            <h3 class="input_headline">Käyttäjänimi:</h3>
                        </div>
                        <div class="input">
                            <input type="text" id="username" name="username"/>
                        </div>

                        <div>
                            <h3 class="input_headline">Salasana:</h3>
                        </div>
                        <div class="input">
                            <input type="password" id="password" name="password"/>
                        </div>
                    </div>

                    <div class="login_container">
                        <div>
                            <button type="submit" class="button" name="login_button">Kirjaudu!</button>
                        </div>

                        <p id="login_text_container">tai</p>

                        <div id="create_account_link_box">
                            <a class="links" href="<?= site_url('create_account') ?>" >luo tunnus -></a>
                        </div>
                    </div>


                    <?php if(isset($_GET['error'])): ?> 
                    <div class="error">
                        <h3>Kirjautuminen epäonnistui :(</h3>
                    </div>
                    <?php endif ?>

                </div>
            </form>
        </div>   
    </div>

    <?=$snippets["footer"]?>

<script type="text/javascript" src=<?= site_url("js/scripts.js") ?>></script>
</body>
</html>
