<!DOCTYPE html>
<html>

<?=$snippets["head_and_theme"]?>

<body>
        
    <?=$snippets["header"]?>

    <div class="bottom">

        <?=$snippets["navi"]?>

        <div class="desc">
            <div>
                <h2 class="text_headline">Projektin lisäys</h2>
            </div>

            <form method="POST" action="<?= site_url("hobby-add_project") ?>" enctype="multipart/form-data">
                <div class="text">

                    <?php if(isset($_GET['error'])): ?>
                        <div class="error">
                            <h3>Projektin lisäys epäonnistui :(</h3>
                        </div>
                    <?php endif ?>

                    <!-- Project type -->
                    <fieldset class="project_data_section">
                        <legend>Projektityyppi:</legend>
                        <div>
                            <input type="radio" class="radio" id="radio_crochet" name="project_type" value="crochet" required>
                            <label for="radio_crochet">Virkatut hahmot</label>
                        </div>
                        <div>
                            <input type="radio" class="radio" id="radio_textile" name="project_type" value="textile" required>
                            <label for="radio_textile">Tekstiilityöt</label>
                        </div>
                        <div>
                            <input type="radio" class="radio" id="radio_tech" name="project_type" value="tech" required>
                            <label for="radio_tech">Tekniset työt</label>
                        </div>
                        <div>
                            <input type="radio" class="radio" id="radio_other" name="project_type" value="other" required>
                            <label for="radio_other">Muut käsityöt</label>
                        </div>
                    </fieldset>
                    <!---->

                    <!-- Project desc -->
                    <fieldset class="project_data_section">
                        <legend>Projektin kuvaus:</legend>
                        <textarea type="text" id="hobby_project_desc" name="project_desc" required></textarea>
                    </fieldset>
                    <!---->

                    <!-- Image data -->
                    <fieldset class="project_data_section">
                        <legend>Kuvatiedot:</legend>
                        <table id="image_data_form">
                            <tr>
                                <!-- Labels for image data -->
                                <th>Kuvatiedosto: (.jpg/.png/.jpeg)</th>
                                <th>Kuvan nimi:</th>
                                <th></th>
                                <th>Laajakuva:</th>
                            <!---->
                            </tr>
                            <tr>
                                <!-- Input fields for image data -->
                                <th><input type="file" id="image_src" name="image_src[]" required></th>
                                <th><input type="text" id="image_name" name="image_name[]" required></th>
                                <th><input type="hidden" name="wide_image[]" value="0"></th>
                                <th><input type="checkbox" id="wide_image" name="wide_image[]" value="1"></th>
                                <!---->
                                <!-- Add more images button -->
                                <th><input type="button" class="button" onclick="add_project_image()" id="add_image_button" name="add_image_button" value="Lisää"></th>
                                <!---->
                            </tr>
                        </table>
                    </fieldset>
                    <!---->

                    <!-- Send button -->
                    <button type="submit" name="add_project_button" id="add_project_button" class="button">
                        Lisää projekti
                    </button>
                    <!---->
                </div>
            </form>
        </div>
    </div>

    <?=$snippets["footer"]?>

<script type="text/javascript" src=<?= file_path("js", "scripts.js") ?>></script>
</body>
</html>
