<!DOCTYPE html>
<html>

<?=$snippets["head_and_theme"]?>

<body>
        
    <?=$snippets["header"]?>

    <div class="bottom">

        <?=$snippets["navi"]?>

        <div class="desc">
            <div>
                <h2 class="text_headline">Projektin lisäys</h2>
            </div>
            <form method="POST" action="<?= site_url("hobby-add_project") ?>">
                <div class="text">
                    <!-- Project type -->
                    <fieldset class="project_data_section">
                        <legend>Projektityyppi:</legend>
                        <div>
                            <input type="checkbox" class="checkbox" id="checkbox_crochet" name="checkbox_crochet"/>
                            <label for="checkbox_crochet">Virkatut hahmot</label>
                        </div>
                        <div>
                            <input type="checkbox" class="checkbox" id="checkbox_textile" name="checkbox_textile"/>
                            <label for="checkbox_textile">Tekstiilityöt</label>
                        </div>
                        <div>
                            <input type="checkbox" class="checkbox" id="checkbox_tech" name="checkbox_tech"/>
                            <label for="checkbox_tech">Tekniset työt</label>
                        </div>
                        <div>
                            <input type="checkbox" class="checkbox" id="checkbox_other" name="checkbox_other"/>
                            <label for="checkbox_other">Muut käsityöt</label>
                        </div>
                    </fieldset>
                    <!---->

                    <!-- Project desc -->
                    <fieldset class="project_data_section">
                        <legend>Projektin kuvaus:</legend>
                        <textarea type="text" id="hobby_project_desc" name="hobby_project_desc"></textarea>
                    </fieldset>
                    <!---->

                    <!-- Image data -->
                    <fieldset class="project_data_section">
                        <legend>Kuvatiedot:</legend>
                        <table id="image_data_form">
                            <tr>
                                <!-- Labels for image data -->
                                <th>Kuvan tiedostonimi: (.jpg/.png/.jpeg)</th>
                                <th>Kuvan nimi:</th>
                                <th>Laajakuva:</th>
                            <!---->
                            </tr>
                            <tr>
                                <!-- Input fields for image data -->
                                <th><input type="text" id="image_name_info" name="image_name_info" required=""></th>
                                <th><input type="text" id="project_name_info" name="project_name_info" required=""></th>
                                <th><input type="checkbox" class="checkbox" id="wide_image_info" name="wide_image_info"></th>
                                <!---->
                                <!-- Add more images button -->
                                <th><input type="button" class="button" onclick="add_project_image()" id="add_image_button" name="add_image_button" value="Lisää"></th>
                                <!---->
                            </tr>
                        </table>
                    </fieldset>
                    <!---->

                    <!-- Send button -->
                    <button type="submit" name="add_project_button" id="add_project_button" class="button">
                        Lisää projekti
                    </button>
                    <!---->
                </div>
            </form>
        </div>
    </div>

    <?=$snippets["footer"]?>

<script type="text/javascript" src=<?= file_path("js", "scripts.js") ?>></script>
</body>
</html>
