<?php

// HELPER FUNCTIONS FOR FORMATTING

function add_project_in_list( array $projects, int $project_ordinal ) : void {
    echo "<li class='ordered_list_item'>";
    echo    $projects["project_desc"];
    echo "</li>";
}

function add_project_image( array $projects, int $project_ordinal) : void {
    $image_data = $projects["image_data"];
    for ($i = 0; $i < count($image_data); $i++) {
        if ($image_data[$i]["is_wide"] == false) {
            $name_class_container = 'image_container';
            $name_class_image = 'proj_img';
        } else {
            $name_class_container = 'wide_image_container';
            $name_class_image = 'wide_img';
        }

        $small_image = site_url("img/projects/" . (pathinfo($image_data[$i]["src"], PATHINFO_FILENAME) . "-small." . pathinfo($image_data[$i]["src"], PATHINFO_EXTENSION)));
        $image = site_url("img/projects/" . $image_data[$i]["src"]);

        echo "<div class=" . $name_class_container . " style='background-image:" .
             sprintf("url(%s)'>", $small_image);
        echo    "<img src=" . $image .
                " class=" . $name_class_image .
                " loading='lazy'" . sprintf(" onclick='enlarge_image(\"%s\")'>", $image);
        echo    "<div class='overlay'>" . $image_data[$i]["name"] . "</div>";
        echo "</div>";
    }
}

?>

<!-------------------------------- THE ACTUAL PAGE -------------------------------->

<!DOCTYPE html>
<html>

<?=$snippets["head_and_theme"]?>

<body>
        
    <?=$snippets["header"]?>

    <div class="bottom">

        <?=$snippets["navi"]?>

        <div class="desc">

            <!-- Page text area -->
            <h2 class="main_text_headline">
                Askarteluja
            </h2>
            <p class="text">
                <?= $params["texts"]["desc_hobby"] ?>
            </p>
            <!---->

            <!-- Crocheted figurines -->
            <h3 class="text_headline" id="crochet">
                Virkatut hahmot
            </h3>
            <p class="text">
                <?= $params["texts"]["hobby_crochet"] ?>
            <ol class="items">
                <?php
                    for ($i = 0; $i < $params["counts"]["crochet"]; $i++) {
                        add_project_in_list($params["projects"]["crochet"][$i], $i);
                    }
                ?>
            </ol>
            <br>&emsp;
            </p>

            <div class="image_area">
                <?php
                    for ($i = 0; $i < $params["counts"]["crochet"]; $i++) {
                        add_project_image($params["projects"]["crochet"][$i], $i);
                    }
                ?>
            </div>
            <!---->

            <!-- Textile work -->
            <h3 class="text_headline" id="textile">
                Tekstiilityöt
            </h3>
            <p class="text">
                <?= $params["texts"]["hobby_textile"] ?>
            <ol class="items">
                <?php
                    for ($i = 0; $i < $params["counts"]["textile"]; $i++) {
                        add_project_in_list($params["projects"]["textile"][$i], $i);
                    }
                ?>
            </ol>
            </p>

            <div class="image_area">
                <?php
                    for ($i = 0; $i < $params["counts"]["textile"]; $i++) {
                        add_project_image($params["projects"]["textile"][$i], $i);
                    }
                ?>
            </div>
            <!---->

            <!-- Technical work -->
            <h3 class="text_headline" id="tech">
                Tekniset työt
            </h3>
            <p class="text">
                <?= $params["texts"]["hobby_tech"] ?>
            <ol class="items">
                <?php
                    for ($i = 0; $i < $params["counts"]["tech"]; $i++) {
                        add_project_in_list($params["projects"]["tech"][$i], $i);
                    }
                ?>
            </ol>
            </p>

            <div class="image_area">
                <?php
                    for ($i = 0; $i < $params["counts"]["tech"]; $i++) {
                        add_project_image($params["projects"]["tech"][$i], $i);
                    }
                ?>
            </div>
            <!---->
            
            <!-- Other crafts -->
            <h3 class="text_headline" id="other">
                Muut käsityöt
            </h3>
            <p class="text">
                <?= $params["texts"]["hobby_other"] ?>
            <ol class="items">
                <?php
                    for ($i = 0; $i < $params["counts"]["other"]; $i++) {
                        add_project_in_list($params["projects"]["other"][$i], $i);
                    }
                ?>
            </ol>
            </p>

            <div class="image_area">
                <?php
                    for ($i = 0; $i < $params["counts"]["other"]; $i++) {
                        add_project_image($params["projects"]["other"][$i], $i);
                    }
                ?>
            </div>
            <!---->

            <!-- Admin area -->
            <?php if($params["user_params"]["is_admin"]): ?> 
            <div class="text">
                <a class="admin_link" href="<?= site_url('hobby-update_text') ?>">Päivitä tekstejä</a>
                <a class="admin_link" href="<?= site_url('hobby-add_project') ?>">Lisää projekti</a>
                <a class="admin_link" href="<?= site_url('hobby-delete_project') ?>">Poista projekti</a>
            </div>
            <?php endif ?>
            <!---->

        </div>

        <!-- Background for the image enlargement  -->
        <div id="enlarged_image_view" onclick="close_image()">
            <div id="image_background"></div>
            <div id="enlarged_image_container">
                <img id="enlarged_image" src="" />
            </div>
        </div>
        <!---->
    </div>

    <?=$snippets["footer"]?>

<script type="text/javascript" src=<?= site_url("js/scripts.js") ?>></script>
</body>
</html>
