<?php

require_once "hobby_projects.php";

// HELPER FUNCTIONS FOR FORMATTING

function add_img_path( string $img ) : string {
    $path = file_path("projects", $img);
    return $path;
}

function add_project_in_list( array $projects_type, int $project_ordinal ) : void {
    echo "<li class='ordered_list_item'>";
    echo    $projects_type[$project_ordinal][1];
    echo "</li>";
}

function add_project_image( array $projects_type, int $project_ordinal) : void {
    $image_list = $projects_type[$project_ordinal][2];
    for ($i = 0; $i < count($image_list); $i++) {
        if ($image_list[$i][1] == false) {
            $name_class_container = 'image_container';
            $name_class_image = 'proj_img';
        } else {
            $name_class_container = 'wide_image_container';
            $name_class_image = 'wide_img';
        }

        $small_image = pathinfo($image_list[$i][0], PATHINFO_FILENAME) . "-small." . pathinfo($image_list[$i][0], PATHINFO_EXTENSION);

        echo "<div class=" . $name_class_container . " style='background-image:" .
             sprintf("url(%s)'>", file_path("projects", $small_image));
        echo    "<img src=" . $image_list[$i][0] .
                " class=" . $name_class_image .
                " loading='lazy'" .
                sprintf(" onclick='enlarge_image(\"%s\")'>", $image_list[$i][0]);
        echo    "<div class='overlay'>" . $image_list[$i][2] . "</div>";
        echo "</div>";
    }
}

?>

<!-------------------------------- THE ACTUAL PAGE -------------------------------->

<!DOCTYPE html>
<html>

<?=$snippets["head_and_theme"]?>

<body>
        
    <?=$snippets["header"]?>

    <div class="bottom">

        <?=$snippets["navi"]?>

        <div class="desc">

            <!-- Page text area -->
            <h2 class="main_text_headline">
                Askarteluja
            </h2>
            <p class="text">
                <?= $params["texts"]["desc_hobby"] ?>
            </p>
            <!---->

            <!-- Crocheted figurines -->
            <h3 class="text_headline" id="crochet">
                Virkatut hahmot
            </h3>
            <p class="text">
                <?= $params["texts"]["hobby_crochet"] ?>
            <ol class="items">
                <?php
                    for ($i = 0; $i < count($character_projects); $i++) {
                        add_project_in_list($character_projects, $i);
                    }
                ?>
            </ol>
            <br>&emsp;
            </p>

            <div class="image_area">
                <?php
                    for ($i = 0; $i < count($character_projects); $i++) {
                        add_project_image($character_projects, $i);
                    }
                ?>
            </div>
            <!---->

            <!-- Textile work -->
            <h3 class="text_headline" id="textile">
                Tekstiilityöt
            </h3>
            <p class="text">
                <?= $params["texts"]["hobby_textile"] ?>
            <ol class="items">
                <?php
                    for ($i = 0; $i < count($textile_projects); $i++) {
                        add_project_in_list($textile_projects, $i);
                    }
                ?>
            </ol>
            </p>

            <div class="image_area">
                <?php
                    for ($i = 0; $i < count($textile_projects); $i++) {
                        add_project_image($textile_projects, $i);
                    }
                ?>
            </div>
            <!---->

            <!-- Technical work -->
            <h3 class="text_headline" id="tech">
                Tekniset työt
            </h3>
            <p class="text">
                <?= $params["texts"]["hobby_tech"] ?>
            <ol class="items">
                <?php
                    for ($i = 0; $i < count($technical_projects); $i++) {
                        add_project_in_list($technical_projects, $i);
                    }
                ?>
            </ol>
            </p>

            <div class="image_area">
                <?php
                    for ($i = 0; $i < count($technical_projects); $i++) {
                        add_project_image($technical_projects, $i);
                    }
                ?>
            </div>
            <!---->
            
            <!-- Other crafts -->
            <h3 class="text_headline" id="other">
                Muut käsityöt
            </h3>
            <p class="text">
                <?= $params["texts"]["hobby_other"] ?>
            <ol class="items">
                <?php
                    for ($i = 0; $i < count($other_projects); $i++) {
                        add_project_in_list($other_projects, $i);
                    }
                ?>
            </ol>
            </p>

            <div class="image_area">
                <?php
                    for ($i = 0; $i < count($other_projects); $i++) {
                        add_project_image($other_projects, $i);
                    }
                ?>
            </div>
            <!---->

            <!-- Admin area -->
            <?php if($params["user_params"]["is_admin"]): ?> 
            <div class="text">
                <a class="admin_link" href="<?= site_url('hobby-update_text') ?>">Päivitä tekstejä</a>
                <a class="admin_link" href="<?= site_url('hobby-add_project') ?>">Lisää projekti</a>
            </div>
            <?php endif ?>
            <!---->

        </div>

        <!-- Background for the image enlargement  -->
        <div id="enlarged_image_view" onclick="close_image()">
            <div id="image_background"></div>
            <div id="enlarged_image_container">
                <img id="enlarged_image" src="" />
            </div>
        </div>
        <!---->
    </div>

    <?=$snippets["footer"]?>

<script type="text/javascript" src=<?= file_path("js", "scripts.js") ?>></script>
</body>
</html>
