<!DOCTYPE html>
<html>

<?=$snippets["head_and_theme"]?>

<body>
        
    <?=$snippets["header"]?>

    <div class="bottom">

        <?=$snippets["navi"]?>

        <div class="desc">

            <form method="POST" action="<?= site_url("hobby-update_text") ?>">
                <!-- Page text area -->
                <h2 class="main_text_headline">
                    Askarteluja
                </h2>
                <form method="POST" action="<?= site_url("hobby-update") ?>">
                <p class="text">
                    <textarea name="desc_hobby_text" class="update_box">
                        <?= $params["texts"]["desc_hobby"] ?>
                    </textarea>
                </p>
                <!---->
    
                <!-- Crocheted figurines -->
                <h3 class="text_headline" id="crochet">
                    Virkatut hahmot
                </h3>
                <p class="text">
                    <textarea name="desc_hobby_crochet_text" class="update_box">
                        <?= $params["texts"]["hobby_crochet"] ?>
                    </textarea>
                </p>
    
                <!-- Textile work -->
                <h3 class="text_headline" id="textile">
                    Tekstiilityöt
                </h3>
                <p class="text">
                    <textarea name="desc_hobby_textile_text" class="update_box">
                        <?= $params["texts"]["hobby_textile"] ?>
                    </textarea>
                </p>
    
                <!-- Technical work -->
                <h3 class="text_headline" id="tech">
                    Tekniset työt
                </h3>
                <p class="text">
                    <textarea name="desc_hobby_tech_text" class="update_box">
                        <?= $params["texts"]["hobby_tech"] ?>
                    </textarea>
                </p>
                
                <!-- Other crafts -->
                <h3 class="text_headline" id="other">
                    Muut käsityöt
                </h3>
                <p class="text">
                    <textarea name="desc_hobby_other_text" class="update_box">
                        <?= $params["texts"]["hobby_other"] ?>
                    </textarea>
                </p>

                <!-- Update button -->
                <button type="submit" name="update_desc_hobby_button" class="button update_button">
                    Päivitä
                </button>
            </form>

            <!-- Cancel button -->
            <a href="<?= site_url("hobby_projects") ?>">
                <button class="button cancel_button">
                    Peruuta
                </button>
            </a>
        </div>
    </div>

    <?=$snippets["footer"]?>

<script type="text/javascript" src=<?= file_path("js", "scripts.js") ?>></script>
</body>
</html>
