<!DOCTYPE html>
<html>

<?=$snippets["head_and_theme"]?>

<body>
        
    <?=$snippets["header"]?>

    <div class="bottom">

        <?=$snippets["navi"]?>
        
        <div class="desc">

            <!-- Page text area -->
            <div>
                <h2 class="main_text_headline">
                    Heipä hei ja tervetuloa katsomaan verkkoprojektejani!
                </h2>
                <p class="text">
                    <?= $params["texts"]["desc_coding"] ?>
                </p>
            </div>
            <!---->

            <!-- Project "Pekkaspäivät" -->
            <h3 class="text_headline" id="pekkaspaivat">
                Pekkaspäivät
            </h3>
            <p class="text">
                <?= $params["texts"]["coding_pekkaspaivat"] ?>
            </p>
            <p class="text">
                <a class="links" href="/Pekkaspaivat/index.php" target="_blank">
                    Tästä linkistä pääset tutustumaan Pekkaspäiviin!
                </a>
            </p>
            <!---->

            <!-- Project "Nettikasvio" -->
            <h3 class="text_headline" id="nettikasvio">
                Nettikasvio
            </h3>
            <p class="text">
                <?= $params["texts"]["coding_nettikasvio"] ?>
            </p>
            <p class="text">
                <a class="links" href="/Nettikasvio/index.php" target="_blank">
                    Tästä linkistä pääset tutustumaan Nettikasvioon!
                </a>
            </p>
            <!---->

            <!-- Project "Joulutoivelista" -->
            <h3 class="text_headline" id="joulutoivelista">
                Joulutoivelista
            </h3>
            <p class="text">
                <?= $params["texts"]["coding_joulutoivelista"] ?>
            </p>
            <p class="text">
                <a class="links" href="/Toivelista/index.php" target="_blank">
                    
                </a>
            </p>
            <!---->

            <!-- Admin area -->
            <?php if($params["user_params"]["is_admin"]): ?> 
            <div class="text">
                <a class="admin_link" href="<?= site_url('coding-update_text') ?>">Päivitä tekstejä</a>
            </div>
            <?php endif ?>
            <!---->
        </div>
    </div>

    <?=$snippets["footer"]?>

<script type="text/javascript" src=<?= file_path("js", "scripts.js") ?>></script>
</body>
</html>
