<!DOCTYPE html>
<html>

<?=$snippets["head_and_theme"]?>

<body>
        
    <?=$snippets["header"]?>

    <div class="bottom">

        <?=$snippets["navi"]?>
        
        <div class="desc">

            <!-- Admin area -->
            <?php if($params["user_params"]["is_admin"]): ?>
            <div>
                <a class="admin_link" href="<?= site_url('coding-update_text') ?>">Päivitä tekstejä</a>
            </div>
            <?php endif ?>
            <!---->

            <!-- Page text area -->
            <div>
                <h2 class="main_text_headline">
                    Heipä hei ja tervetuloa katsomaan verkkoprojektejani!
                </h2>
                <div class="text">
                    <p class="text_with_whitespace"><?= $params["texts"]["desc_coding"] ?></p>
                </div>
            </div>
            <!---->

            <!-- Project "Pekkaspäivät" -->
            <h3 class="text_headline" id="pekkaspaivat">
                Pekkaspäivät
            </h3>
            <div class="text">
                <p class="text_with_whitespace"><?= $params["texts"]["coding_pekkaspaivat"] ?></p>
            </div>
            <p class="text">
                <a class="links" href="https://pekkaspaivat.ropaz.dev" target="_blank">Tästä linkistä pääset tutustumaan Pekkaspäiviin!</a>
            </p>
            <!---->

            <!-- Project "Nettikasvio" -->
            <h3 class="text_headline" id="nettikasvio">
                Nettikasvio
            </h3>
            <div class="text">
                <p class="text_with_whitespace"><?= $params["texts"]["coding_nettikasvio"] ?></p>
            </div>
            <p class="text">
                <a class="links" href="https://nettikasvio.ropaz.dev" target="_blank">Tästä linkistä pääset tutustumaan Nettikasvioon!</a>
            </p>
            <!---->

            <!-- Project "Joulutoivelista" -->
            <h3 class="text_headline" id="joulutoivelista">
                Joulutoivelista
            </h3>
            <div class="text">
                <p class="text_with_whitespace"><?= $params["texts"]["coding_joulutoivelista"] ?></p>
            </div>
            <p class="text">
                <a class="links" href="https://toivelista.ropaz.dev" target="_blank"></a>
            </p>
            <!---->
        </div>
    </div>

    <?=$snippets["footer"]?>

<script type="text/javascript" src=<?= site_url("js/scripts.js") ?>></script>
</body>
</html>
