<!DOCTYPE html>
<html>

<?=$snippets["head_and_theme"]?>

<body>
    
    <?=$snippets["header"]?>

    <div class="bottom">

        <?=$snippets["navi"]?>
        
        <div class="desc">
            <h1 class="text_headline">401: Hetkinen, tänne ei ole pääsyä kuin harvoilla ja valituilla! 👮</h1>
            <p class="text"></p>
        </div>

    </div>

    <?=$snippets["footer"]?>

<script type="text/javascript" src=<?= file_path("js", "scripts.js") ?>></script>
</body>
</html>
