<!DOCTYPE html>
<html>

<?=$snippets["head_and_theme"]?>

<body>
    
    <?=$snippets["header"]?>

    <div class="bottom">

        <?=$snippets["navi"]?>
        
        <div class="desc">
            <h1 class="text_headline">404: Harmi juttu, sivua ei löytynyt! 😿</h1>
            <p class="text">Koitahan navigoida tiesi navigaattorin kautta →</p>
        </div>

    </div>

    <?=$snippets["footer"]?>

<script type="text/javascript" src=<?= site_url("/js/scripts.js") ?>></script>
</body>
</html>
