<!DOCTYPE html>
<html>

<?=$snippets["head_and_theme"]?>

<body>
    
    <?=$snippets["header"]?>

    <div class="bottom">

        <?=$snippets["navi"]?>
        
        <div class="desc">
            <h1 class="text_headline">500: Harmi juttu, jotain meni pieleen! 😿</h1>
            <p class="text">Onneksi tästä voidaan syyttää sivujen tekijää!</p>
        </div>

    </div>

    <?=$snippets["footer"]?>

<script type="text/javascript" src=<?= site_url("js/scripts.js") ?>></script>
</body>
</html>
